<PenggunaScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Selamat datang, Pengguna!'
        Button:
            text: 'Kembali ke Login'
            on_release: app.root.current = 'login'

<PetugasScreen>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Selamat datang, Petugas!'
        Button:
            text: 'Kembali ke Login'
            on_release: app.root.current = 'login'
